apiVersion: v1
kind: Secret
metadata:
  name: nginx-helm-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
  type: helm
