apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bitnami-system
    server: 'https://kubernetes.default.svc'
  source:
    path: 'sealed-secrets'
    repoURL: 'https://bitnami-labs.github.io'
    targetRevision: {{ .Values.version.sealedSecrets }}
    chart: sealed-secrets
  project: e2e-monitor
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
