iapiVersion: v1
kind: Secret
metadata:
  name: certmanager-helm-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: jetstack
  url: https://charts.jetstack.io
  type: helm
