apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: certmanager-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: 'cert-manager'
    repoURL: 'https://charts.jetstack.io'
    targetRevision: "v0.15.1"
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
  project: e2e-monitor
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
