# ingress-nginx version 2.0.3 doesn't seem to include an IngressClass with the helm chart.
apiVersion: networking.k8s.io/v1beta1
kind: IngressClass
metadata:
  name: nginx
spec:
  controller: k8s.io/ingress-nginx