apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: snapshot-policy
  namespace: default
data:
  snapshot-policy.json: |
    {
      "name": "weekly-snap-{now}",
      "schedule": "0 0 0 ? * 1",
      "repository": "gcs-snapshot-repo",
      "config": {}
    }
