kind: Secret
apiVersion: v1
metadata:
  name: gcs-credentials
  namespace: default
  annotations:
    avp.kubernetes.io/path: "secret/ci/elastic-cloud/eck/argocd/gcs-credentials"
type: Opaque
stringData:
  gcs.client.default.credentials_file: <gcs.client.default.credentials_file>