kind: Secret
apiVersion: v1
metadata:
  name: e2e-monitor-issuer-account-key
  namespace: cert-manager
  annotations:
    avp.kubernetes.io/path: "secret/ci/elastic-cloud/eck/argocd/e2e-monitor-issuer-account-key"
type: Opaque
stringData:
  tls.key: <tls.key>